import os
from dotenv import load_dotenv
load_dotenv()
from apify_client import ApifyClient
from app.utils.metadata import (
    normalize_metadata,
    normalize_transcript
)
APIFY_TOKEN_2 = os.getenv("APIFY_TOKEN_2")

client = ApifyClient(
    APIFY_TOKEN_2
)


def extract_transcript(item):

    subtitles = item.get("subtitles") or []

    if not subtitles:
        return []

    subtitle = subtitles[0]

    srt = subtitle.get("srt")

    if not srt:
        return []

    return [{
        "start": 0,
        "end": 0,
        "text": srt
    }]


def get_youtube_audio_url(url):

    run_input = {
        "video_urls": [
            {
                "url": url,
                "method": "GET"
            }
        ]
    }

    run = client.actor(
        "scrapearchitect/youtube-audio-mp3-downloader"
    ).call(
        run_input=run_input
    )
    
    dataset = client.dataset(
        run.default_dataset_id
    )
    item = next(
        dataset.iterate_items(),
        None
    )

    if not item:
        raise Exception(
            "No audio data returned"
        )

    tracks = item.get(
        "downloadable_audio_links",
        []
    )

    if not tracks:
        raise Exception(
            "No audio tracks found"
        )

    english = [
        t for t in tracks
        if (
            t.get(
                "language",
                ""
            ).lower().startswith("en")
        )
    ]

    if english:
        return english[0]["url"]

    return tracks[0]["url"]


def get_youtube_data(url):

    run_input = {
        "startUrls": [
            {
                "url": url
            }
        ],
        "downloadSubtitles": True,
        "saveSubsToKVS": False,
        "subtitlesLanguage": "en",
        "preferAutoGeneratedSubtitles": True,
        "subtitlesFormat": "srt"
    }

    run = client.actor(
        "streamers/youtube-scraper"
    ).call(
        run_input=run_input
    )

    dataset = client.dataset(
        run.default_dataset_id
    )

    item = next(
        dataset.iterate_items(),
        None
    )

    if not item:
        raise Exception(
            "No data returned from Apify"
        )

    raw_metadata = {
        "title": item.get("title"),
        "creator": item.get("channelName"),
        "views": item.get("viewCount"),
        "likes": item.get("likes"),
        "comments": item.get("commentsCount"),
        "duration": item.get("duration"),
        "upload_date": item.get("date"),
        "thumbnail": item.get("thumbnailUrl"),
        "description": item.get("text"),
        "platform": "youtube"
    }

    return {
        "metadata": normalize_metadata(
            raw_metadata
        ),
        "transcript": normalize_transcript(
            extract_transcript(item)
        )
    }