from apify_client import ApifyClient
from app.utils.metadata import (
    normalize_metadata,
    normalize_transcript
)

import os



client = ApifyClient(
    os.getenv("APIFY_TOKEN2")
)



def extract_transcript(item):

    subtitles = item.get("subtitles") or []

    if not subtitles:
        return []

    subtitle = subtitles[0]

    srt = subtitle.get("srt")

    if not srt:
        return []

    return [{
        "start": 0,
        "end": 0,
        "text": srt
    }]


def get_best_audio_url(item):

    tracks = item.get(
        "downloadable_audio_links",
        []
    )

    if not tracks:
        return None

    english_tracks = [
        track
        for track in tracks
        if (
            track.get(
                "language",
                ""
            )
            .lower()
            .startswith("en")
        )
    ]

    if english_tracks:
        return english_tracks[0]["url"]

    return tracks[0]["url"]


def get_youtube_data(url):

    run_input = {
        "startUrls": [
            {
                "url": url
            }
        ],
        "downloadSubtitles": True,
        "subtitlesLanguage": "en",
        "preferAutoGeneratedSubtitles": True,
        "subtitlesFormat": "srt"
    }

    run = client.actor(
        "streamers/youtube-scraper"
    ).call(
        run_input=run_input
    )

    items = list(
        client.dataset(
            run["defaultDatasetId"]
        ).iterate_items()
    )

    if not items:
        raise Exception(
            "No data returned from Apify"
        )

    item = items[0]

    raw_metadata = {
        "title": item.get("title"),
        "creator": item.get("channelName"),
        "views": item.get("viewCount"),
        "likes": item.get("likes"),
        "comments": item.get("commentsCount"),
        "duration": item.get("duration"),
        "upload_date": item.get("date"),
        "thumbnail": item.get("thumbnailUrl"),
        "description": item.get("text"),
        "platform": "youtube"
    }

    return {
        "metadata": normalize_metadata(
            raw_metadata
        ),
        "transcript": normalize_transcript(
            extract_transcript(item)
        ),
        "audio_url": get_best_audio_url(
            item
        )
    }