from apify_client import ApifyClient
from dotenv import load_dotenv

from app.utils.metadata import (
    normalize_metadata,
    normalize_transcript
)

import os
import httpx

load_dotenv()

client = ApifyClient(
    os.getenv("APIFY_TOKEN_2")
)


def extract_transcript(item):

    subtitles = item.get("subtitles") or []

    if not subtitles:
        return []

    srt = subtitles[0].get("srt")

    if not srt:
        return []

    return [{
        "start": 0,
        "end": 0,
        "text": srt
    }]


def get_audio_download_url(video_id):

    response = httpx.get(
        f"https://ytjar.p.rapidapi.com/dl/{video_id}",
        params={
            "wait_until_the_file_is_ready": "true",
            "quality": "low"
        },
        headers={
            "X-RapidAPI-Key":
                os.getenv("RAPIDAPI_KEY"),
            "X-RapidAPI-Host":
                "ytjar.p.rapidapi.com"
        },
        timeout=600
    )

    response.raise_for_status()

    data = response.json()

    if "link" not in data:
        raise Exception(
            f"Audio link not found: {data}"
        )

    return data["link"]


def get_youtube_data(url):

    run_input = {
        "startUrls": [
            {
                "url": url
            }
        ],
        "downloadSubtitles": True,
        "saveSubsToKVS": False,
        "subtitlesLanguage": "en",
        "preferAutoGeneratedSubtitles": True,
        "subtitlesFormat": "srt"
    }

    run = client.actor(
        "streamers/youtube-scraper"
    ).call(
        run_input=run_input
    )

    dataset = client.dataset(
        run.default_dataset_id
    )

    item = next(
        dataset.iterate_items(),
        None
    )

    if not item:
        raise Exception(
            "No data returned from Apify"
        )
    print(item.keys())
    print(item.get("duration"))
    raw_metadata = {
        "title": item.get("title"),
        "creator": item.get("channelName"),
        "views": item.get("viewCount"),
        "likes": item.get("likes"),
        "comments": item.get("commentsCount"),
        "duration": item.get("duration"),
        "upload_date": item.get("date"),
        "thumbnail": item.get("thumbnailUrl"),
        "description": item.get("text"),
        "platform": "youtube"
    }

    transcript = normalize_transcript(
        extract_transcript(item)
    )

    return {
        "metadata": normalize_metadata(
            raw_metadata
        ),
        "transcript": transcript,
        "video_id": item.get("id")
    }